version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mlflow

  mlflow:
    build: ./mlflow
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow:/mlflow

  airflow:
    build:
      context: .
      dockerfile: airflow/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
